#!/usr/bin/env python3
"""Shim. The sitemap is generated by ../run_sitemap.py - this file only forwards.

Until 2026-08-26 this script carried its own URL list, and that list was the
pre-v4 site: /en/, /en/services-en/, /en/about-en/ (all now 301s), the Academy
pages (noindex on purpose), and the two Smart Website offer pages as raw .html
URLs. The article workflow runs THIS file after every publish, so each new
article silently overwrote the v4-aware sitemap with a stale one, and the
deployed sitemap.xml listed redirects and noindexed pages while listing none of
the v4 URLs.

One list, in one file. Add or retire a URL in run_sitemap.py, not here.
"""
import os
import runpy
import sys

repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
target = os.path.join(repo_root, "run_sitemap.py")

if not os.path.isfile(target):
    sys.exit("run_sitemap.py not found at " + target)

# run_sitemap.py resolves "public_html" relative to the working directory, and
# reads git history from the repo it sits in, so it has to run from there.
os.chdir(repo_root)
runpy.run_path(target, run_name="__main__")
