#!/usr/bin/env python3
"""
Re-skin the two article hubs onto the v4 brand-book template.

    python3 tools/reskin_blog_hubs.py --dry-run     # report, write nothing
    python3 tools/reskin_blog_hubs.py               # rewrite both hubs
    python3 tools/reskin_blog_hubs.py --lang ar     # one hub
    python3 tools/reskin_blog_hubs.py --out /tmp/p  # write elsewhere

`public_html/blog/index.html` (EN) and `public_html/blog-ar/index.html` (AR)
were the last two pages still on the old dark Tailwind-CDN skin, which left
them looking like a different site from the 300 articles they link to. Both are
rewritten IN PLACE - the URLs are indexed and every article's chrome links back
to them.

Where the content comes from
----------------------------
Nothing on either hub is typed by hand. Every card's headline, description,
category, hero image, date and reading time is read off the published article
at build time, so the hub cannot drift from the corpus: publish an article and
re-run this, and it appears. The old hubs carried the same 150 cards as literal
markup, which is why they had to be regenerated by `update_blog_hubs.py` and
why a stale card could sit there unnoticed.

What is preserved
-----------------
Both canonicals, the Organization/ProfessionalService JSON-LD block (address,
CR, phone, geo and sameAs byte for byte from the old hubs), the GA measurement
id, and the full set of 150 article links per language.

What is fixed
-------------
  * The English hub's meta description was written in Arabic. Both hubs now
    describe themselves in their own language.
  * Neither hub declared hreflang, so the EN and AR archives of the same
    corpus competed instead of pairing. Both now point at each other, with
    x-default on the English one.
  * The category filter ran off `update_blog_hubs.py`'s CATEGORY_MAP, which
    knew 25 of the 70+ category strings in use; everything it did not know -
    about half the corpus - silently fell into "Implementation & Automation".
    Buckets are now derived by rule (see BUCKET_RULES) and, because a bucket is
    resolved from the English article and then applied to its Arabic twin, the
    same piece files under the same heading in both languages.
  * Search and filter were separate behaviours that overwrote each other. They
    now compose, and both degrade to "every article listed, newest first".

What is removed
---------------
The Tailwind CDN script, the old dark skin, the FOUC overlay, and
`/js/aiden-chat.js`. The widget is dropped for the same reason the articles
dropped it: `blog_chrome.footer` already puts a WhatsApp action button in the
bottom corner and Aiden's launcher pins to that same corner, so the two overlap.
Note that `tools/add_aiden_widget.py` will put the script tag back on its next
run, on these pages and on all 150 articles.
"""
import argparse
import hashlib
import html as _html
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(HERE / "v4"))

import blog_chrome as C                                   # noqa: E402
from kit import (BASE_CSS, MOTION_JS, SKIP_CSS, STAR, TOKENS,   # noqa: E402
                 WA, WA_ICON)

BLOG = ROOT / "public_html" / "blog"
ASSETS = ROOT / "public_html" / "assets"
SITE = "https://aiprofitlab.io"
WPM = {"en": 225, "ar": 190}

# Where each hub is written and what URL it answers on. The Arabic hub sits at
# /blog-ar/ while Arabic articles sit under /blog/ar/ - an inconsistency in the
# live URL structure that predates this script and is not worth a redirect.
HUBS = {
    "en": {"file": ROOT / "public_html" / "blog" / "index.html", "url": SITE + "/blog/"},
    "ar": {"file": ROOT / "public_html" / "blog-ar" / "index.html", "url": SITE + "/blog-ar/"},
}

# How many cards render before "show more". All 150 are in the DOM either way -
# this only controls what is painted, so every article stays crawlable and
# stays findable by the in-page search.
PAGE = 24


# --------------------------------------------------------------------------
# Buckets
# --------------------------------------------------------------------------
# Six filters over 70+ author-written category strings. Order is significant:
# the first rule whose keyword appears wins, so "Data Security & Compliance"
# resolves to law before "security" could pull it anywhere else, and
# "Enterprise CRM Automation" reaches `systems` only after the law and
# customer rules have declined it.
BUCKET_RULES = [
    ("law", ("security", "governance", "complian", "privacy", "legal", "pdpl",
             "sovereign", "cyber", "data protection", "regulat", "law")),
    ("customers", ("whatsapp", "receptionist", "customer service", "customer support",
                   "customer trust", "communication", "chatbot", "lead", "crm")),
    ("sectors", ("case stud", "real estate", "retail", "e-commerce", "ecommerce",
                 "healthcare", "education", "government", "tourism", "energy",
                 "oil", "gas", "logistics", "finance", "fintech", "automotive",
                 "space", "manufactur", "construction", "hospitality", "banking")),
    ("money", ("roi", "pricing", "cost", "strategy", "ceo", "invest", "profit",
               "thought leadership", "budget")),
    ("systems", ("automation", "implementation", "integrat", "tools", "workflow",
                 "efficiency", "infrastructure", "cloud", "api", "agents",
                 "models", "technology", "innovation", "news", "transformation")),
]

BUCKETS = {
    "en": [("all", "Everything"), ("customers", "WhatsApp &amp; customers"),
           ("money", "Strategy &amp; ROI"), ("systems", "Automation &amp; systems"),
           ("law", "Data, security &amp; law"), ("sectors", "Sectors &amp; case studies")],
    "ar": [("all", "كل المقالات"), ("customers", "واتساب والعملاء"),
           ("money", "الاستراتيجية والعائد"), ("systems", "الأتمتة والأنظمة"),
           ("law", "البيانات والأمن والقانون"), ("sectors", "القطاعات ودراسات الحالة")],
}


def bucket(entry):
    """Resolve one article to one filter key.

    The category is the strongest signal, but seven articles carry none and a
    number carry one so generic it says nothing ("AI Tools"), so the headline
    and the page's own keywords are searched as a fallback before the default.
    """
    for haystack in (entry["cat"].lower(),
                     " ".join((entry["title"], entry["tag_title"], entry["kw"])).lower()):
        if not haystack.strip():
            continue
        for key, words in BUCKET_RULES:
            if any(w in haystack for w in words):
                return key
    return "systems"


# --------------------------------------------------------------------------
# Copy
# --------------------------------------------------------------------------
# Arabic strings here have NOT been checked by a native speaker. Everything
# that already existed in blog_chrome.T is reused rather than rewritten, so
# what is new is only the hero, the search affordances and the closing block.
T = {
    "en": {
        "eyebrow": "Articles",
        "h1": "Notes from the work",
        "lede": ("Every article here comes out of a system built for someone in Oman or the wider "
                 "Gulf &mdash; WhatsApp response gaps, owner dashboards, what automation actually "
                 "costs, and where the PDPL draws the line. All of it published in English and "
                 "Arabic."),
        "search_label": "Search articles",
        "search_ph": "Search %d articles &mdash; try ROI, WhatsApp, PDPL, Muscat",
        "clear": "Clear search",
        "filter_label": "Filter by topic",
        "count_one": "1 article", "count_many": "%d articles",
        "latest": "Latest",
        "archive": "The archive",
        "more": "Show more articles",
        "empty_h": "Nothing filed under that yet.",
        "empty_p": ("Ask the question directly and you will get an answer &mdash; and it will "
                    "probably become an article afterwards."),
        "read": "min read",
        "cta_eyebrow": "Not covered here",
        "cta_h": "Ask the question you actually have",
        "cta_p": ("These answer what people ask most often. Yours is probably more specific than "
                  "that &mdash; send it and you get an answer from the person who builds the "
                  "systems, not a form reply."),
        "cta_btn": "Ask on WhatsApp",
        "cta_wa": "Hello%20Nahid%2C%20I%20have%20a%20question%20I%20did%20not%20find%20an%20article%20about.",
        "cta_alt": "Run the numbers instead",
        "title": "Articles | AI Profit Lab &mdash; AI automation writing from Muscat, Oman",
        "desc": ("%d articles on WhatsApp AI receptionists, owner dashboards, automation cost and "
                 "Oman's PDPL - written by the operator who builds the systems, in English and Arabic."),
        "schema_name": "AI Profit Lab &mdash; Articles",
    },
    "ar": {
        "eyebrow": "المقالات",
        "h1": "ملاحظات من العمل",
        "lede": ("كل مقال هنا خرج من نظام بُني فعلياً لعميل في عُمان أو الخليج &mdash; الرسائل التي "
                 "لا يُرد عليها على واتساب، ولوحات المتابعة للملّاك، والتكلفة الحقيقية للأتمتة، وأين "
                 "يضع قانون حماية البيانات الشخصية الحد. وكل ذلك منشور بالعربية والإنجليزية."),
        "search_label": "ابحث في المقالات",
        "search_ph": "ابحث في %d مقال &mdash; جرّب: واتساب، العائد، البيانات، مسقط",
        "clear": "مسح البحث",
        "filter_label": "تصفية حسب الموضوع",
        "count_one": "مقال واحد", "count_many": "%d مقال",
        "latest": "الأحدث",
        "archive": "الأرشيف",
        "more": "عرض مقالات أخرى",
        "empty_h": "لا يوجد شيء تحت هذا التصنيف بعد.",
        "empty_p": ("اطرح سؤالك مباشرة وستحصل على إجابة &mdash; وغالباً ما يتحوّل السؤال إلى مقال "
                    "بعد ذلك."),
        "read": "دقائق قراءة",
        "cta_eyebrow": "لم تجد ما تبحث عنه",
        "cta_h": "اطرح سؤالك أنت",
        "cta_p": ("هذه المقالات تجيب عن الأسئلة الأكثر تكراراً، وسؤالك على الأرجح أكثر تحديداً "
                  "منها &mdash; أرسله وستصلك إجابة ممّن يبني الأنظمة، لا ردّ آلي من نموذج."),
        "cta_btn": "اسأل على واتساب",
        "cta_wa": "%D9%85%D8%B1%D8%AD%D8%A8%D8%A7%D9%8B%D8%8C%20%D9%84%D8%AF%D9%8A%20"
                  "%D8%B3%D8%A4%D8%A7%D9%84%20%D9%84%D9%85%20%D8%A3%D8%AC%D8%AF%20"
                  "%D9%84%D9%87%20%D9%85%D9%82%D8%A7%D9%84%D8%A7%D9%8B.",
        "cta_alt": "احسب أرقامك بدلاً من ذلك",
        "title": "المقالات | AI Profit Lab &mdash; أتمتة الذكاء الاصطناعي من مسقط",
        "desc": ("%d مقال عن موظف الاستقبال الذكي على واتساب، ولوحات متابعة الملّاك، وتكلفة الأتمتة، "
                 "وقانون حماية البيانات الشخصية العُماني - بالعربية والإنجليزية."),
        "schema_name": "AI Profit Lab - المقالات",
    },
}

# Kept byte for byte from the old hubs. The address, CR, phone, geo point and
# sameAs list were corrected site-wide on 2026-08-18 and re-typing them here
# is exactly how a NAP drifts out of sync.
ORG_SCHEMA = """{
  "@context": "https://schema.org",
  "@type": "ProfessionalService",
  "name": "AI Profit Lab",
  "legalName": "Lotus Gulf International",
  "url": "https://aiprofitlab.io",
  "logo": "https://aiprofitlab.io/logo.webp",
  "image": "https://aiprofitlab.io/og-aiprofitlab-2026.jpg",
  "description": "Helping non-technical managers leverage AI, automation, and technology to increase ROI and business efficiency.",
  "address": {
    "@type": "PostalAddress",
    "streetAddress": "South Al Khuwair, Bousher",
    "addressLocality": "Muscat",
    "addressRegion": "Muscat Governorate",
    "postalCode": "000",
    "addressCountry": "OM"
  },
  "geo": {
    "@type": "GeoCoordinates",
    "latitude": 23.5803,
    "longitude": 58.4310
  },
  "contactPoint": {
    "@type": "ContactPoint",
    "telephone": "+968-99245250",
    "contactType": "customer service",
    "areaServed": "GCC",
    "availableLanguage": ["en", "ar"]
  },
  "sameAs": [
    "https://www.youtube.com/@AI_for_Managers",
    "https://www.linkedin.com/in/nahid-aby"
  ]
}"""


# --------------------------------------------------------------------------
# CSS
# --------------------------------------------------------------------------
HUB_CSS = """
/* ------------------------------------------------------------------ hero */
.hhero .lede{margin:0 0 clamp(30px,3.6vw,42px)}
.hhero .h1{margin:0 0 22px}

/* Visually hidden but read aloud: the search field and the filter group both
   need a name, and neither has room for a visible one. */
.vh{position:absolute;width:1px;height:1px;margin:-1px;padding:0;overflow:hidden;
  clip:rect(0 0 0 0);clip-path:inset(50%);white-space:nowrap;border:0}

/* ---------------------------------------------------------------- search */
.search{position:relative;max-width:620px}
.search input{
  width:100%;font-family:var(--sans);font-size:1rem;color:var(--ink);
  background:var(--white);border:1px solid var(--line);border-radius:99px;
  padding:15px 52px 15px 52px;transition:border-color .2s,box-shadow .2s;
  -webkit-appearance:none;appearance:none;
}
.search input::placeholder{color:var(--taupe)}
.search input:focus{outline:none;border-color:var(--teal);box-shadow:0 0 0 4px rgba(15,110,86,.12)}
.search input::-webkit-search-cancel-button{-webkit-appearance:none}
.search .mag{
  position:absolute;top:50%;inset-inline-start:19px;transform:translateY(-50%);
  width:19px;height:19px;color:var(--muted);pointer-events:none;
}
.search .mag svg{width:100%;height:100%;fill:none;stroke:currentColor;stroke-width:2;
  stroke-linecap:round;stroke-linejoin:round}
.search .clr{
  position:absolute;top:50%;inset-inline-end:9px;transform:translateY(-50%);
  width:34px;height:34px;border:0;border-radius:50%;background:var(--panel-2);
  color:var(--teal-900);cursor:pointer;font-size:1.15rem;line-height:1;
  display:none;align-items:center;justify-content:center;
}
.search .clr:hover{background:var(--line)}
.search.has-q .clr{display:flex}

/* ---------------------------------------------------------------- filter */
.filters{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin-top:clamp(20px,2.4vw,26px)}
.filters button{
  font-family:var(--mono);font-size:.79rem;letter-spacing:.08em;text-transform:uppercase;
  color:var(--teal-900);background:var(--white);border:1px solid var(--line);border-radius:99px;
  padding:9px 17px;cursor:pointer;transition:border-color .2s,background .2s,color .2s,transform .2s;
}
.filters button:hover{border-color:var(--teal);transform:translateY(-1px)}
.filters button[aria-pressed=true]{background:var(--teal-950);border-color:var(--teal-950);color:var(--cream)}
.filters button i{font-style:normal;opacity:.55;margin-inline-start:7px}
.fcount{
  font-family:var(--mono);font-size:.79rem;letter-spacing:.08em;color:var(--muted);
  margin-inline-start:auto;white-space:nowrap;
}

/* -------------------------------------------------------------- featured */
.feat{
  display:grid;grid-template-columns:1.05fr .95fr;background:var(--white);
  border:1px solid var(--line);border-radius:18px;overflow:hidden;text-decoration:none;
  transition:transform .4s var(--ease),box-shadow .4s var(--ease);
}
.feat:hover{transform:translateY(-4px);box-shadow:0 30px 60px -40px rgba(7,43,34,.6)}
/* Every hero in /blog/images/ was drawn for the old navy skin: near-black
   fields of blue and cyan. Dropped straight onto cream they read as holes in
   the page. `article_kit`'s .afig already answered this - inset the art in a
   panel-toned frame so it presents as a mounted plate rather than as the page
   itself - and the hub matting is deliberately the same frame, so a card and
   the article it opens look like one system. */
.feat .shot{background:var(--panel-2);padding:clamp(12px,1.4vw,18px)}
.feat .shot img{display:block;width:100%;height:100%;aspect-ratio:16/10;
  object-fit:cover;border-radius:12px}
.feat .txt{padding:clamp(26px,3.4vw,44px);display:flex;flex-direction:column;justify-content:center}
.feat .tagline{
  font-family:var(--mono);font-size:.74rem;letter-spacing:.16em;text-transform:uppercase;
  color:var(--amber-text);margin:0 0 14px;display:flex;align-items:center;gap:9px;
}
.feat h2{font-size:clamp(1.4rem,2.6vw,2.05rem);line-height:1.14;color:var(--teal-950);margin:0 0 14px}
.feat p{color:var(--muted);font-size:1.02rem;margin:0 0 20px}
.feat .stamp{font-family:var(--mono);font-size:.76rem;letter-spacing:.1em;
  text-transform:uppercase;color:var(--muted)}

/* ------------------------------------------------------------------ grid */
.posts{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:clamp(18px,2.4vw,28px)}
.post{
  display:flex;flex-direction:column;background:var(--panel);border:1px solid var(--line);
  border-radius:16px;overflow:hidden;text-decoration:none;
  transition:transform .35s var(--ease),box-shadow .35s var(--ease),border-color .35s;
}
.post:hover{transform:translateY(-4px);box-shadow:0 26px 50px -34px rgba(7,43,34,.5);border-color:var(--panel-2)}
/* Same matte as .feat. The zoom-on-hover that a bleeding thumbnail can afford
   is gone with it: a scaled image inside a padded frame grows over its own
   mount. The card still answers the pointer by lifting. */
.post .shot{background:var(--panel-2);padding:clamp(9px,1vw,12px)}
.post .shot img{display:block;width:100%;aspect-ratio:16/9;object-fit:cover;border-radius:11px}
.post .txt{padding:clamp(20px,2.2vw,26px);display:flex;flex-direction:column;flex:1}
.post .kicker{font-family:var(--mono);font-size:.72rem;letter-spacing:.14em;text-transform:uppercase;
  color:var(--amber-text);margin:0 0 11px}
.post h3{font-size:clamp(1.06rem,1.5vw,1.22rem);line-height:1.26;color:var(--teal-950);margin:0 0 10px}
.post p{color:var(--muted);font-size:.95rem;line-height:1.55;margin:0 0 18px}
.post .stamp{
  margin-top:auto;padding-top:14px;border-top:1px solid var(--line);
  font-family:var(--mono);font-size:.73rem;letter-spacing:.09em;text-transform:uppercase;
  color:var(--muted);display:flex;justify-content:space-between;gap:10px;
}
/* .post is display:flex, which beats the [hidden] UA rule, so the filter's
   hidden attribute needs saying again here or nothing ever disappears. */
.post[hidden]{display:none}

/* ------------------------------------------------------------ show more */
.more-row{display:flex;justify-content:center;margin-top:clamp(34px,4vw,52px)}
.more{
  font-family:var(--mono);font-size:.82rem;letter-spacing:.1em;text-transform:uppercase;
  color:var(--teal-950);background:transparent;border:1px solid var(--teal-950);
  border-radius:99px;padding:15px 34px;cursor:pointer;
  transition:background .25s,color .25s;
}
.more:hover{background:var(--teal-950);color:var(--cream)}
.more[hidden]{display:none}

.empty{border:1px dashed var(--line);border-radius:16px;padding:clamp(30px,5vw,60px);
  text-align:center;color:var(--muted);margin-top:24px}
.empty[hidden]{display:none}
.empty b{display:block;font-family:var(--display);font-size:1.3rem;color:var(--teal-950);
  font-weight:400;margin-bottom:8px}

/* --------------------------------------------------- no-JS / no-behaviour */
/* Nothing above is load-bearing for reading the archive. Without the script
   the page is 150 cards, newest first, and the three controls that would do
   nothing are not shown at all rather than shown broken. */
html:not(.js) .search,
html:not(.js) .filters,
html:not(.js) .more-row{display:none}
html:not(.js) .post[hidden]{display:flex}
/* …except the newest article's duplicate card, which only exists so the
   search can return it. The panel above is already showing that article, and
   with no script running the panel never goes away. Must follow the rule
   above: equal specificity, so source order decides. */
html:not(.js) .post[data-feat]{display:none}

@media (max-width:1080px){
  /* minmax(0,…) on every track: a card's <img> carries a width attribute, so
     the automatic minimum of a plain 1fr track is that image's own width and
     the grid quietly grows past a phone viewport. */
  .posts{grid-template-columns:repeat(2,minmax(0,1fr))}
  /* Stacked, the shot has no row height to inherit, so height:100% goes
     indefinite and the img's own aspect-ratio takes over sizing it. That is
     why the ratio lives on the img and there is no min-height anywhere: the
     pair together would set an automatic minimum in the INLINE axis and push
     the card past the viewport. */
  .feat{grid-template-columns:minmax(0,1fr)}
}
@media (max-width:640px){
  .posts{grid-template-columns:minmax(0,1fr)}
  .fcount{width:100%;margin:4px 0 0}
}
"""

HUB_RTL_CSS = """
/* --------------------------------------------------- Arabic hub overrides */
/* The hero heading is display type; Markazi Text sits smaller on the body than
   Marcellus does, so the Latin clamp leaves it undersized. */
[dir=rtl] .hhero .h1{font-size:clamp(2.2rem,4.6vw,3.4rem);line-height:1.28}
[dir=rtl] .feat h2{font-size:clamp(1.5rem,2.8vw,2.2rem);line-height:1.34}
[dir=rtl] .post h3{font-size:clamp(1.14rem,1.6vw,1.32rem);line-height:1.45}
/* Tracked, upper-cased small text is a Latin device: on Arabic it separates
   letters that must join and the label stops being a word. */
[dir=rtl] .filters button,[dir=rtl] .fcount,[dir=rtl] .more,
[dir=rtl] .feat .tagline,[dir=rtl] .feat .stamp,
[dir=rtl] .post .kicker,[dir=rtl] .post .stamp{letter-spacing:0;text-transform:none}
[dir=rtl] .search input{font-size:1.02rem}
/* Deliberately NO direction:ltr on the date. blog_chrome forces LTR on .num
   because a bare figure like "OMR 1,023" comes out reversed in Arabic, and
   the same rule applied here looks like it should help - the day and year are
   Western digits. It does the opposite. "18 أغسطس 2026" is not a number, it
   is an RTL phrase with digits in it, and forcing the run LTR strands the
   year between the day and the month: 18 2026 أغسطس. Left alone, the bidi
   algorithm puts the day on the right and the year on the left, which is the
   order an Arabic reader expects. */
"""


def stylesheet():
    """The one stylesheet both hubs link. Order matters: tokens, the shared v4
    design system, this page's own components, then the two RTL layers last so
    they win. `article_kit`'s prose CSS is deliberately absent - a hub has no
    prose."""
    return TOKENS + SKIP_CSS + BASE_CSS + HUB_CSS + C.RTL_CSS + HUB_RTL_CSS


# --------------------------------------------------------------------------
# JS
# --------------------------------------------------------------------------
HUB_JS = r"""
/* ---------------------------------------------------------------------------
   Archive controls: topic filter, text search and progressive reveal, over one
   server-rendered list. There is no second copy of the data and no fetch - the
   cards are the index - so with the script absent the page is still the whole
   archive, newest first.
--------------------------------------------------------------------------- */
(function(){
  "use strict";
  var grid = document.getElementById("posts");
  if (!grid) return;

  var bar    = document.getElementById("filters");
  var input  = document.getElementById("q");
  var wrap   = document.getElementById("searchbox");
  var clear  = document.getElementById("qclear");
  var count  = document.getElementById("fcount");
  var empty  = document.getElementById("empty");
  var more   = document.getElementById("more");
  var feat   = document.getElementById("featured");
  var PAGE   = parseInt(grid.getAttribute("data-page") || "24", 10);
  var ONE    = grid.getAttribute("data-one");
  var MANY   = grid.getAttribute("data-many");

  /* Arabic is written with optional vowel marks, four spellings of alef and a
     taa marbuta that readers type as either ة or ه. Folding both the haystack
     and the needle through the same normaliser is what makes "اتمتة" find an
     article filed under "أتمتة". Harmless on Latin text, so it runs on both. */
  function norm(s){
    return (s || "").toLowerCase()
      .replace(/[ً-ْٰـ]/g, "")
      .replace(/[آأإٱ]/g, "ا")
      .replace(/ى/g, "ي")
      .replace(/ة/g, "ه")
      .replace(/\s+/g, " ")
      .trim();
  }

  /* The searchable string is normalised once per card, not once per keystroke. */
  var cards = [].slice.call(grid.querySelectorAll(".post")).map(function(el){
    return {el: el, cat: el.getAttribute("data-cat"), feat: el.hasAttribute("data-feat"),
            s: norm(el.getAttribute("data-s"))};
  });

  /* `q` is always an array of normalised terms - never a string, never null.
     One shape means matches() has no type test to get wrong, and an empty
     array is the honest representation of "nothing typed". */
  var cat = "all", q = [], shown = PAGE;

  function matches(c){
    if (cat !== "all" && c.cat !== cat) return false;
    for (var i = 0; i < q.length; i++){ if (c.s.indexOf(q[i]) === -1) return false; }
    return true;
  }

  function apply(){
    /* The featured panel is the unfiltered, unsearched view only: with a
       filter or a query active it would sit above the results contradicting
       them. While it shows, it stands in for its own card in the grid. */
    var featOn = (cat === "all" && q.length === 0);
    if (feat) feat.hidden = !featOn;

    var hits = 0, painted = 0;
    for (var i = 0; i < cards.length; i++){
      var c = cards[i];
      var vis;
      if (c.feat && featOn){
        vis = false;                       /* the panel is showing it instead */
      } else {
        var on = matches(c);
        if (on) hits++;
        /* Two reasons a card can be out: it did not match, or it matched but
           sits past the reveal line. Only the first is "no results", which is
           why hits is counted before this test. */
        vis = on && painted < shown;
        if (vis) painted++;
      }
      if (c.el.hidden === vis) c.el.hidden = !vis;
    }

    /* The panel is one of the articles on show, so it counts as one. */
    var total = hits + (featOn ? 1 : 0);
    if (count) count.textContent = total === 1 ? ONE : MANY.replace("%d", total);
    if (empty) empty.hidden = total > 0;
    if (more)  more.hidden  = hits <= painted;
    if (wrap)  wrap.classList.toggle("has-q", !!(input && input.value));
  }

  if (bar) bar.addEventListener("click", function(e){
    var b = e.target.closest("button");
    if (!b) return;
    cat = b.getAttribute("data-cat");
    shown = PAGE;
    [].forEach.call(bar.querySelectorAll("button"), function(x){
      x.setAttribute("aria-pressed", x === b ? "true" : "false");
    });
    apply();
    if (typeof gtag === "function") gtag("event", "filter_articles", {category: cat});
  });

  if (input){
    var timer;
    input.addEventListener("input", function(){
      /* Split on whitespace so the terms can appear in any order and in any
         of the fields folded into data-s. */
      q = norm(input.value).split(" ").filter(Boolean);
      shown = PAGE;
      apply();
      clearTimeout(timer);
      timer = setTimeout(function(){
        if (q.length && typeof gtag === "function")
          gtag("event", "search_articles", {search_term: input.value.trim()});
      }, 900);
    });
    input.addEventListener("keydown", function(e){ if (e.key === "Escape") reset(); });
  }

  function reset(){
    if (input) input.value = "";
    q = []; shown = PAGE; apply(); if (input) input.focus();
  }
  if (clear) clear.addEventListener("click", reset);

  if (more) more.addEventListener("click", function(){
    /* The first card of the batch about to appear, captured before it does.
       Once the button hides itself on the last batch it can no longer hold
       focus, and a keyboard user would be dropped back to the top of the
       document with no indication anything happened. */
    var first = grid.querySelectorAll(".post:not([hidden])").length;
    shown += PAGE;
    apply();
    if (more.hidden){
      var visible = grid.querySelectorAll(".post:not([hidden])");
      /* Each card is an <a href>, so it is already focusable - no tabindex
         needed, and adding one would pull it out of the tab order. */
      var target = visible[first] || visible[visible.length - 1];
      if (target) target.focus();
    }
  });

  apply();
})();
"""


# --------------------------------------------------------------------------
# Reading the corpus
# --------------------------------------------------------------------------
def _meta(head, name, prop=False):
    attr = "property" if prop else "name"
    m = re.search(r'<meta %s="%s" content="([^"]*)"' % (attr, name), head)
    return _html.unescape(m.group(1)).strip() if m else ""


def read_articles(lang):
    """One dict per published article, keyed by slug."""
    out = {}
    for f in sorted((BLOG / lang).glob("*.html")):
        src = f.read_text(encoding="utf-8")
        head = src[:src.find("</head>")] if "</head>" in src else src[:12000]

        m = re.search(r"<title>(.*?)</title>", head, re.S)
        tag_title = _html.unescape(m.group(1)).strip() if m else f.stem
        tag_title = re.sub(r"\s*\|\s*AI Profit Lab.*$", "", tag_title).strip()

        # The card shows the article's own <h1>, not its <title>. Six English
        # articles carry a <title> that was cut off mid-word by whatever wrote
        # them ("Arabic | AI Profit Lab", "How Businesses in Dubai Are Using
        # Wh... |"), and all 300 have an intact <h1>. The <title> is also the
        # SEO string rather than the headline, so even where it is whole the
        # <h1> is the better card text. The <title> is kept for the search
        # index, where its extra keywords are worth something.
        m = re.search(r'<h1 class="h1">(.*?)</h1>', src, re.S)
        title = _html.unescape(re.sub(r"<[^>]+>", "", m.group(1))).strip() if m else ""
        if not title:
            title = tag_title

        img = _meta(head, "og:image", prop=True)
        if img.startswith(SITE):
            img = img[len(SITE):]

        date = _meta(head, "article:published_time", prop=True)
        if not re.match(r"\d{4}-\d{2}-\d{2}$", date):
            m = re.match(r"(\d{4}-\d{2}-\d{2})", f.stem)
            date = m.group(1) if m else ""

        body = re.search(r'<article class="prose">(.*?)</article>', src, re.S)
        words = len(re.sub(r"<[^>]+>", " ", body.group(1)).split()) if body else 0

        out[f.stem] = {
            "slug": f.stem,
            "title": title,
            "tag_title": tag_title,
            "desc": _meta(head, "description"),
            "kw": _meta(head, "keywords"),
            "cat": _meta(head, "category"),
            "img": img or "/blog/images/default.png",
            "date": date,
            "words": words,
            # Always the trailing-slash form. 242 of the 300 articles declare a
            # canonical without one, and .htaccess 301s that shape to this one,
            # so linking the canonical as written would send every reader and
            # every crawler through a redirect on the way in.
            "url": "/blog/%s/%s/" % (lang, f.stem),
        }
    return out


# --------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------
def _esc(s):
    """Unescape first: the source pages mix raw characters with named entities
    inside the same attribute, and escaping those directly would double-encode
    the ampersand and publish the literal text."""
    return _html.escape(_html.unescape(s or ""), quote=True)


def _kicker(e, lang, labels):
    """The article's own category is more specific than its bucket, so it is
    what the card shows. On the Arabic hub a category left in English is
    replaced by the bucket's Arabic label rather than printed as-is."""
    cat = e["cat"].strip()
    if cat and lang == "ar" and not re.search(r"[؀-ۿ]", cat):
        cat = ""
    return _html.unescape(cat) if cat else _html.unescape(labels[e["bucket"]])


def _mins(e, lang):
    return max(1, round(e["words"] / WPM[lang]))


def card(e, lang, labels, t, hidden, feat=False):
    """One archive card. `data-s` is the search index for this article: the
    fields a reader would plausibly type against, in one attribute, so the
    filter never has to touch the DOM text.

    The newest article gets a card here as well as the display panel above,
    marked `data-feat`. Without it the piece most likely to be looked for is
    the one piece the search cannot return, because the panel is not part of
    the filtered list. The card is suppressed exactly while the panel shows it.
    """
    idx = " ".join((e["title"], e["tag_title"], e["desc"], e["cat"], e["kw"])).lower()
    return (
        '<a class="post"%s href="%s" data-cat="%s" data-s="%s"%s>'
        '<div class="shot"><img src="%s" alt="" loading="lazy" decoding="async" '
        'width="420" height="236"></div>'
        '<div class="txt">'
        '<p class="kicker">%s</p>'
        '<h3>%s</h3>'
        '<p>%s</p>'
        '<span class="stamp"><time datetime="%s">%s</time><span>%d %s</span></span>'
        '</div></a>'
        % (' data-feat=""' if feat else "",
           _esc(e["url"]), e["bucket"], _esc(re.sub(r"\s+", " ", idx)),
           " hidden" if hidden else "",
           _esc(e["img"]), _esc(_kicker(e, lang, labels)), _esc(e["title"]),
           _esc(e["desc"]), _esc(e["date"]), _esc(C.fmt_date(e["date"], lang)),
           _mins(e, lang), t["read"])
    )


def head(lang, total, css_href, js_href):
    t = T[lang]
    u = HUBS[lang]["url"]
    other = HUBS["ar" if lang == "en" else "en"]["url"]
    fonts = C.FONTS_AR if lang == "ar" else C.FONTS_EN
    direction = "rtl" if lang == "ar" else "ltr"
    desc = t["desc"] % total
    title = _html.unescape(t["title"])

    # Both hubs list the same 150 articles in two languages, which is the exact
    # case hreflang exists for. Neither hub declared any before this.
    alts = "\n".join([
        '<link rel="alternate" hreflang="en" href="%s">' % HUBS["en"]["url"],
        '<link rel="alternate" hreflang="ar" href="%s">' % HUBS["ar"]["url"],
        '<link rel="alternate" hreflang="x-default" href="%s">' % HUBS["en"]["url"],
    ])

    return f"""<!DOCTYPE html>
<html dir="{direction}" lang="{'ar' if lang == 'ar' else 'en'}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
<title>{_esc(title)}</title>
<meta name="description" content="{_esc(desc)}">
<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1">
<link rel="canonical" href="{u}">
{alts}
<link rel="icon" type="image/svg+xml" href="/favicon.svg">
<link rel="apple-touch-icon" href="/favicon.svg">

<meta property="og:type" content="website">
<meta property="og:site_name" content="AI Profit Lab">
<meta property="og:title" content="{_esc(title)}">
<meta property="og:description" content="{_esc(desc)}">
<meta property="og:url" content="{u}">
<meta property="og:image" content="{SITE}/og-aiprofitlab-2026.jpg">
<meta property="og:locale" content="{'ar_OM' if lang == 'ar' else 'en_OM'}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{_esc(title)}">
<meta name="twitter:description" content="{_esc(desc)}">
<meta name="twitter:image" content="{SITE}/og-aiprofitlab-2026.jpg">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="preload" as="style" href="{fonts}">
<link rel="stylesheet" media="print" onload="this.media='all'" href="{fonts}">
<noscript><link rel="stylesheet" href="{fonts}"></noscript>
<!-- Content-hashed, so the host's `immutable, max-age=31536000` rule on
     /assets/** is safe here: an edited stylesheet ships under a new filename
     instead of sitting behind a year-long cache on a stale one. -->
<link rel="stylesheet" href="{css_href}">
<script>document.documentElement.className+=" js"</script>

<!-- Google tag (gtag.js) -->
<script defer src="{js_href}"></script>
<script async src="https://www.googletagmanager.com/gtag/js?id=G-SLR9GD3MJP"></script>
<script>window.dataLayer=window.dataLayer||[];function gtag(){{dataLayer.push(arguments)}}gtag('js',new Date());gtag('config','G-SLR9GD3MJP');</script>

<script type="application/ld+json">
{ORG_SCHEMA}
</script>
</head>
<body>
<a class="skip" href="#main">{C.T[lang]["skip"]}</a>
"""


def schema(lang, entries):
    """A Blog node for the hub, a breadcrumb, and the list itself.

    The ItemList carries position and url only. The headline and image already
    sit on the target page and repeating them here is two places to go stale;
    what the list adds that the markup does not is the ORDER, which is the one
    thing a crawler cannot infer from a grid.
    """
    t, u = T[lang], HUBS[lang]["url"]
    items = ",".join(
        '{"@type":"ListItem","position":%d,"url":"%s"}' % (i + 1, SITE + e["url"])
        for i, e in enumerate(entries))
    home = SITE + (C.URLS[lang]["home"])
    return f"""<script type="application/ld+json">
{{"@context":"https://schema.org","@graph":[
{{"@type":"Blog","@id":"{u}#blog","name":"{_html.unescape(t['schema_name'])}","url":"{u}",
  "inLanguage":"{'ar' if lang == 'ar' else 'en'}","description":"{_esc(t['desc'] % len(entries))}",
  "publisher":{{"@type":"Organization","name":"AI Profit Lab","legalName":"Lotus Gulf International","url":"{SITE}"}}}},
{{"@type":"BreadcrumbList","itemListElement":[
  {{"@type":"ListItem","position":1,"name":"{C.T[lang]['crumb_home']}","item":"{home}"}},
  {{"@type":"ListItem","position":2,"name":"{C.T[lang]['crumb_blog']}","item":"{u}"}}]}},
{{"@type":"ItemList","@id":"{u}#articles","name":"{_html.unescape(t['schema_name'])}",
  "numberOfItems":{len(entries)},"itemListOrder":"https://schema.org/ItemListOrderDescending",
  "itemListElement":[{items}]}}
]}}
</script>
"""


def header(lang):
    """`blog_chrome.header` sends the language toggle to the other language's
    HOME page. From an article hub the useful destination is the other hub, so
    the two anchors that carry it are swapped by exact string - a blind replace
    of the href would also hit the logo, which points at the same "/" on the
    English pages."""
    out = C.header(lang)
    u, t = C.URLS[lang], C.T[lang]
    other_lang = "ar" if lang == "en" else "en"
    other_hub = HUBS[other_lang]["url"].replace(SITE, "")
    for old, new in (
        ('<a class="lnk" href="%s" lang="%s">%s</a>' % (u["other"], other_lang, t["other_lang"]),
         '<a class="lnk" href="%s" lang="%s">%s</a>' % (other_hub, other_lang, t["other_lang"])),
        ('<a href="%s" lang="%s"><em>07</em>%s</a>' % (u["other"], other_lang, t["other_lang"]),
         '<a href="%s" lang="%s"><em>07</em>%s</a>' % (other_hub, other_lang, t["other_lang"])),
    ):
        if old not in out:
            raise SystemExit("header(): language toggle markup changed in blog_chrome; "
                             "update reskin_blog_hubs.header()")
        out = out.replace(old, new)
    return out


def render(lang, entries, css_href, js_href):
    t, u = T[lang], C.URLS[lang]
    labels = dict(BUCKETS[lang])
    total = len(entries)
    feat = entries[0]

    used = {}
    for e in entries:
        used[e["bucket"]] = used.get(e["bucket"], 0) + 1

    chips = "\n      ".join(
        '<button type="button" data-cat="%s" aria-pressed="%s">%s<i>%d</i></button>'
        % (key, "true" if key == "all" else "false", label,
           total if key == "all" else used[key])
        for key, label in BUCKETS[lang] if key == "all" or used.get(key))

    # Card 0 is the featured article's duplicate: in the DOM so search can
    # reach it, hidden because the panel above is already showing it. Cards
    # 1..PAGE paint; the rest wait for "show more".
    cards = "\n".join(
        card(e, lang, labels, t, hidden=(i == 0 or i > PAGE), feat=(i == 0))
        for i, e in enumerate(entries))

    body = f"""<main id="main">

<section class="hhero phero s-panel grain">
  <div class="wrap">
    <p class="eyebrow"><span class="star">{STAR}</span>{t["eyebrow"]}</p>
    <h1 class="h1">{t["h1"]}</h1>
    <p class="lede">{t["lede"]}</p>

    <div class="search" id="searchbox">
      <label class="vh" for="q">{t["search_label"]}</label>
      <span class="mag" aria-hidden="true"><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="M20 20l-3.6-3.6"/></svg></span>
      <input id="q" type="search" autocomplete="off" placeholder="{_esc(t["search_ph"] % total)}">
      <button class="clr" id="qclear" type="button" aria-label="{t["clear"]}">&times;</button>
    </div>

    <div class="filters" id="filters" role="group" aria-label="{t["filter_label"]}">
      {chips}
      <span class="fcount" id="fcount" aria-live="polite">{t["count_many"] % total}</span>
    </div>
  </div>
</section>

<section class="s-cream pad-s" id="featured">
  <div class="wrap">
    <a class="feat rv" href="{_esc(feat["url"])}">
      <div class="shot"><img src="{_esc(feat["img"])}" alt="" width="620" height="420" fetchpriority="high" decoding="async"></div>
      <div class="txt">
        <p class="tagline"><span class="star">{STAR}</span>{t["latest"]}</p>
        <h2>{_esc(feat["title"])}</h2>
        <p>{_esc(feat["desc"])}</p>
        <span class="stamp"><time datetime="{_esc(feat["date"])}">{C.fmt_date(feat["date"], lang)}</time> &middot; {_mins(feat, lang)} {t["read"]}</span>
      </div>
    </a>
  </div>
</section>

<section class="s-cream" style="padding-top:0">
  <div class="wrap">
    <div class="asterism"><span>{STAR}</span></div>
    <h2 class="vh">{t["archive"]}</h2>
    <div class="posts" id="posts" data-page="{PAGE}" data-one="{t["count_one"]}" data-many="{t["count_many"]}">
{cards}
    </div>
    <div class="empty" id="empty" hidden>
      <b>{t["empty_h"]}</b>
      <p style="margin:0">{t["empty_p"]}</p>
    </div>
    <div class="more-row">
      <button class="more" id="more" type="button">{t["more"]}</button>
    </div>
  </div>
</section>

<section class="s-dark grain">
  <div class="wrap-n" style="text-align:center">
    <p class="eyebrow" style="justify-content:center"><span class="star">{STAR}</span>{t["cta_eyebrow"]}</p>
    <h2 class="h2">{t["cta_h"]}</h2>
    <p class="lede" style="margin-inline:auto">{t["cta_p"]}</p>
    <div class="btn-row" style="justify-content:center;margin-top:26px">
      <a class="btn btn-wa" href="{WA}&text={t["cta_wa"]}">{WA_ICON}<span>{t["cta_btn"]}</span></a>
      <a class="btn btn-ghost" href="{u["sim"]}">{t["cta_alt"]}</a>
    </div>
  </div>
</section>

</main>
"""
    return (head(lang, total, css_href, js_href)
            + header(lang)
            + body
            + C.footer(lang)
            + schema(lang, entries)
            + "</body>\n</html>\n")


# --------------------------------------------------------------------------
# Assets
# --------------------------------------------------------------------------
def build_assets(write=True):
    """One stylesheet and one script for both hubs, under a content-hashed
    filename so /assets/**'s year-long immutable cache can never serve a stale
    copy."""
    out = {}
    for ext, blob in (("css", stylesheet()), ("js", MOTION_JS + HUB_JS)):
        h = hashlib.sha256(blob.encode()).hexdigest()[:10]
        name = f"apl-hub.{h}.{ext}"
        if write:
            d = ASSETS / ext
            d.mkdir(parents=True, exist_ok=True)
            for old in d.glob(f"apl-hub.*.{ext}"):
                if old.name != name:
                    old.unlink()
            (d / name).write_text(blob, encoding="utf-8")
        out[ext] = f"/assets/{ext}/{name}"
    return out["css"], out["js"]


# --------------------------------------------------------------------------
# Driver
# --------------------------------------------------------------------------
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--lang", choices=["en", "ar"], help="only one hub")
    ap.add_argument("--out", help="write into this directory instead of in place")
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()

    css_href, js_href = build_assets(write=not a.dry_run)
    print(f"  assets: {css_href}  {js_href}")

    # Buckets are resolved once, on the English article, then applied to its
    # Arabic twin. Deriving them separately per language would need the rule
    # table written twice and would let the same piece file under two different
    # headings in the two archives.
    src = {lang: read_articles(lang) for lang in ("en", "ar")}
    keys = {}
    for slug, e in src["en"].items():
        keys[slug] = bucket(e)
    for slug, e in src["ar"].items():
        e["bucket"] = keys.get(slug) or bucket(e)
    for slug, e in src["en"].items():
        e["bucket"] = keys[slug]

    for lang in ([a.lang] if a.lang else ["en", "ar"]):
        entries = sorted(src[lang].values(),
                         key=lambda e: (e["date"], e["slug"]), reverse=True)
        html = render(lang, entries, css_href, js_href)
        dest = HUBS[lang]["file"]
        if a.out:
            dest = pathlib.Path(a.out) / ("blog" if lang == "en" else "blog-ar") / "index.html"
        spread = {}
        for e in entries:
            spread[e["bucket"]] = spread.get(e["bucket"], 0) + 1
        note = "  ".join("%s:%d" % kv for kv in sorted(spread.items()))
        if a.dry_run:
            print(f"  would write {HUBS[lang]['file'].relative_to(ROOT)}  "
                  f"{len(html)/1024:.0f} KB  {len(entries)} articles  [{note}]")
        else:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(html, encoding="utf-8")
            shown = dest.relative_to(ROOT) if a.out is None else dest
            print(f"  wrote {shown}  {len(html)/1024:.0f} KB  "
                  f"{len(entries)} articles  [{note}]")


if __name__ == "__main__":
    main()
